# Generated by Django 3.2.5 on 2021-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=20)),
                ('channel_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
