# Generated by Django 3.2.5 on 2022-02-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slack_user_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
