version: '3'
services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - SLACK_API_KEY=xoxp-2307232680805-2303506300838-2315637221683-c1b45610af5b4b842fa3449f5919c835
      - SLACK_USER_API_KEY=xoxp-2307232680805-2303506300838-2315637221683-c1b45610af5b4b842fa3449f5919c835
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - SECRET_KEY=SECRET_KEY
      - ALLOWED_HOSTS=*
    build:
      context: .
      dockerfile: DockerfileLocal
    command: >
      bash -c "ls && ./app/manage.py migrate &&
               ./app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
  celery:
    restart: always
    build:
      context: .
    user: root
    command: >
      celery -A corner_test.celery worker -B -l info --loglevel=DEBUG --without-gossip --without-mingle --without-heartbeat -Ofair --pool=solo
    environment:
      - DJANGO_SECRET_KEY=local
      - SLACK_API_KEY=xoxp-2307232680805-2303506300838-2315637221683-c1b45610af5b4b842fa3449f5919c835
      - SLACK_USER_API_KEY=xoxp-2307232680805-2303506300838-2315637221683-c1b45610af5b4b842fa3449f5919c835
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - SECRET_KEY=SECRET_KEY
      - ALLOWED_HOSTS=*
    depends_on:
      - postgres
      - redis
      - web

  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"

volumes:
  postgres123-data: {}
  redis-data: {}
  static_files: {}