# Generated by Django 3.2.5 on 2022-02-07 22:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='menus.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 7, 22, 56, 7, 390035), unique=True),
        ),
    ]
